---
name: (( param "Please define the deployment name in the environment templates" ))

networks:
  - name: bastion
    type: manual
    subnets: (( param "Please configure the `bastion' network in your site or environment templates" ))

disk_pools:
  - name: bastion
    disk_size: 20_000

resource_pools:
  - name: bastion
    network: bastion
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "Please define the cloud properties for your bastion VMs" ))
